"""Added missing columns to transactions

Revision ID: 0380bb794fa9
Revises: ac7e49c0c61d
Create Date: 2025-02-09 16:17:14.592201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0380bb794fa9'
down_revision: Union[str, None] = 'ac7e49c0c61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('account_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('account_iban', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('additional_information', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('category', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('budget_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('categorized', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('manual_flag', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('author', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('manually_reviewed', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('month', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'year')
    op.drop_column('transactions', 'month')
    op.drop_column('transactions', 'manually_reviewed')
    op.drop_column('transactions', 'author')
    op.drop_column('transactions', 'manual_flag')
    op.drop_column('transactions', 'categorized')
    op.drop_column('transactions', 'budget_type')
    op.drop_column('transactions', 'category')
    op.drop_column('transactions', 'additional_information')
    op.drop_column('transactions', 'account_iban')
    op.drop_column('transactions', 'account_name')
    # ### end Alembic commands ###
