"""Updated database models

Revision ID: ac7e49c0c61d
Revises: 
Create Date: 2025-02-09 15:23:39.292309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7e49c0c61d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE budget_type ALTER COLUMN is_shared_expense TYPE BOOLEAN USING is_shared_expense::BOOLEAN")

    op.alter_column('sync_log', 'timestamp',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('transactions', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('creditor_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('creditor_iban', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('debtor_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('debtor_iban', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('remittance_info', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('bank_transaction_code', sa.String(), nullable=True))
    op.drop_constraint('transactions_transaction_id_key', 'transactions', type_='unique')
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.drop_column('transactions', 'manually_reviewed')
    op.drop_column('transactions', 'category')
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('manually_reviewed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.create_unique_constraint('transactions_transaction_id_key', 'transactions', ['transaction_id'])
    op.drop_column('transactions', 'bank_transaction_code')
    op.drop_column('transactions', 'remittance_info')
    op.drop_column('transactions', 'debtor_iban')
    op.drop_column('transactions', 'debtor_name')
    op.drop_column('transactions', 'creditor_iban')
    op.drop_column('transactions', 'creditor_name')
    op.drop_column('transactions', 'currency')
    op.alter_column('sync_log', 'timestamp',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('budget_type', 'is_shared_expense',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
